M48
; DRILL file KiCad 10.0.3 date 2026-09-25T22:19:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T22:19:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.450
%
G90
G05
T1
X116.5Y-89.07
T2
X100.5Y-97.58
X116.5Y-152.82
M30
